apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx-app
    name: nginx-deploy
    env: dev
    client: gtuc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      name: nginx-temp
      labels:
        app: nginx-app
        env: dev
        client: gtuc
    spec:
      containers:
        - name: nginx-cont
          image: nginx
          ports:
            - containerPort: 80
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx-app
spec:
  selector:
    app: nginx-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 80